from pathlib import Path
from html import escape
from datetime import date

ROOT = Path(__file__).parent
OUT = ROOT / "dist"
ASSETS = OUT / "assets"
DOMAIN = "https://hotwaterorange.com"
EMAIL = "info@hotwaterorange.com"
LEAD_EMAIL = "inforank@gmx.com"

SERVICES = {
    "repairs": ("Hot Water Repairs", "Practical fault guidance for leaking, inconsistent or failed hot-water systems."),
    "replacement": ("System Replacement", "Compare replacement pathways when an older unit is unreliable, corroded or poorly matched."),
    "heat-pump": ("Heat Pump Hot Water", "Understand cold-climate performance, positioning, noise, tariffs and upgrade considerations."),
    "electric": ("Electric Hot Water", "Storage-system repairs, elements, thermostats, sizing and replacement planning."),
    "gas": ("Gas Hot Water", "Guidance for storage and continuous-flow systems, ignition faults and replacement decisions."),
    "continuous-flow": ("Continuous-Flow Systems", "Space-conscious hot-water options sized around household demand and available energy."),
    "system-upgrades": ("Hot Water Upgrades", "Plan a more efficient, practical system when household needs or energy priorities change."),
}

LOCATIONS = {
    "orange": ("Orange", "Cold winters, regular frosts and a wide mix of established homes, newer estates and rental properties make careful system sizing particularly important."),
    "blayney": ("Blayney", "Cool Tablelands conditions and winter demand mean insulation, recovery time and external-system placement deserve close attention."),
    "millthorpe": ("Millthorpe", "Heritage character, renovated homes and cold mornings can create very different access, capacity and installation requirements."),
    "molong": ("Molong", "Household size, property layout, water quality, energy source and travel considerations should all be clarified before recommending work."),
    "lucknow": ("Lucknow", "Homes near Orange may still differ in access, existing services and system exposure, so a clear description and photographs help prepare an accurate response."),
    "spring-hill": ("Spring Hill", "Frost and exposed outdoor positions can influence pipe protection, system placement and day-to-day winter performance."),
    "borenore": ("Borenore", "Semi-rural access, household demand and the distance between the unit and outlets can shape replacement and upgrade decisions."),
}

FAQS = [
    ("Why has my hot water suddenly stopped?", "A complete loss of hot water can result from a power or gas supply problem, a tripped safety device, a failed element or thermostat, ignition trouble, a leak, or an ageing cylinder. Check only safe household controls you already understand. Do not remove covers or work around exposed wiring, gas or very hot water. Include the system type, approximate age, symptoms and any visible error code in your enquiry."),
    ("Should a leaking hot-water system be repaired or replaced?", "It depends on where the water is coming from. A valve, fitting or accessible component may be repairable. Water escaping from a corroded storage tank usually points towards replacement. Turn off the relevant supply only if you know how to do so safely, keep people away from electrical hazards, and arrange an assessment."),
    ("Which hot-water system suits Orange's cold climate?", "There is no single answer for every home. The right option depends on household size, peak demand, available energy, installation space, electrical capacity, budget, noise sensitivity and the performance data for the exact model. Heat pumps can work in cool climates, but model selection and placement matter."),
    ("Can I ask for advice before choosing a system?", "Yes. A useful enquiry includes the current unit, household size, usual shower pattern, available gas or electrical supply, roof or outdoor space, what is going wrong and whether your priorities are lower running cost, fast recovery, lower upfront cost or reduced emissions."),
    ("How long does replacement take?", "Timing varies with product availability, safe access, the condition of existing connections, whether the replacement is like-for-like, and whether electrical, plumbing, gas or structural changes are required. A provider should confirm scope and timing after reviewing the property rather than promising a universal timeframe."),
    ("Are NSW hot-water rebates guaranteed?", "No. Programs, eligibility rules, approved products and accredited-provider requirements can change. Check current NSW Government or energy-program information and ask the eventual provider to explain eligibility before relying on a rebate in your budget."),
]

def icon(name):
    paths = {
        "drop": '<path d="M12 2S5 10 5 15a7 7 0 0 0 14 0c0-5-7-13-7-13Z"/><path d="M9 16c.6 1.2 1.5 1.8 3 2"/>',
        "leaf": '<path d="M20 4C12 4 5 8 5 15c0 3 2 5 5 5 7 0 10-8 10-16Z"/><path d="M4 21c3-6 7-9 12-12"/>',
        "sun": '<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',
        "tool": '<path d="M14.7 6.3a4 4 0 0 0-5-5L12 3.6 8.4 7.2 6.1 4.9a4 4 0 0 0 5 5L4 17a2 2 0 1 0 3 3l7.1-7.1a4 4 0 0 0 5-5l-2.3 2.3-3.6-3.6 1.5-1.3Z"/>',
    }
    return f'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>'

def nav():
    return '''<header class="site-header"><a class="brand" href="/"><span class="brand-mark">OH</span><span>Orange Hot Water<small>Orange NSW and nearby towns</small></span></a><button class="menu" aria-expanded="false" aria-controls="nav">Menu</button><nav id="nav"><a href="/services/">Services</a><a href="/locations/">Areas</a><a href="/advice/">Advice</a><a href="/about/">About</a><a class="nav-cta" href="/contact/">Request a quote</a></nav></header>'''

def footer():
    return f'''<footer><div class="footer-grid"><div><div class="footer-brand">Orange Hot Water</div><p>An independent online enquiry service for hot-water needs in Orange and selected nearby communities.</p></div><div><h2>Explore</h2><a href="/services/">Services</a><a href="/locations/">Service areas</a><a href="/faq/">Hot-water FAQ</a><a href="/advice/">Practical advice</a></div><div><h2>Enquiries</h2><a href="mailto:{EMAIL}">{EMAIL}</a><a href="/contact/">Send an enquiry</a><p class="muted">No phone number is currently displayed.</p></div></div><div class="legal"><span>© {date.today().year} Orange Hot Water</span><span><a href="/privacy/">Privacy</a> · <a href="/terms/">Terms</a> · <a href="/disclaimer/">Disclaimer</a></span></div></footer>'''

def faq_block(items=FAQS):
    return '<div class="faq-list">' + ''.join(f'<details><summary>{escape(q)}</summary><p>{escape(a)}</p></details>' for q,a in items) + '</div>'

def cta(title="Tell us what is happening"):
    return f'''<section class="cta"><div><p class="eyebrow">Clear information helps</p><h2>{title}</h2><p>Describe the current system, suburb, symptoms and what you need. Your enquiry can then be matched with a suitable local provider.</p></div><a class="button light" href="/contact/">Request a quote</a></section>'''

def layout(title, desc, body, path, schema_type="WebPage"):
    canonical = DOMAIN + (path if path.endswith('/') else path + '/')
    schema = f'''{{"@context":"https://schema.org","@type":"{schema_type}","name":{title!r},"description":{desc!r},"url":"{canonical}","isPartOf":{{"@type":"WebSite","name":"Orange Hot Water","url":"{DOMAIN}/"}}}}'''.replace("'", '"')
    return f'''<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(desc)}"><link rel="canonical" href="{canonical}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{canonical}"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">{schema}</script></head><body>{nav()}<main>{body}</main>{footer()}<script src="/assets/site.js" defer></script></body></html>'''

def write(path, html):
    target = OUT / path.strip('/') / "index.html" if path != "/" else OUT / "index.html"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(html, encoding="utf-8")

def hero(title, intro, image="hero-autumn-twilight.webp", eyebrow="Hot water for Orange's climate"):
    return f'''<section class="page-hero" style="--hero:url('/assets/{image}')"><div class="hero-shade"></div><div class="hero-copy"><p class="eyebrow">{escape(eyebrow)}</p><h1>{escape(title)}</h1><p>{escape(intro)}</p><a class="button" href="/contact/">Request a quote</a></div></section>'''

def home():
    cards = ''.join(f'''<a class="card service-card" href="/services/{slug}/"><span>{icon('tool')}</span><h3>{name}</h3><p>{desc}</p><b>Explore this service →</b></a>''' for slug,(name,desc) in SERVICES.items())
    body = hero("Hot water help shaped for Orange", "Repairs, replacement planning and system upgrades for cold mornings, changing seasons and the way your household actually uses hot water.")
    body += f'''<section class="intro split"><div><p class="eyebrow">A clearer starting point</p><h2>When the water runs cold, useful questions come first</h2><p>A failed or unreliable hot-water system can disrupt an entire household. Orange Hot Water helps residents explain the problem, compare sensible options and request contact from an appropriate provider without pretending every home needs the same answer.</p><p>Orange's frost, cool winters and marked seasonal changes make system selection more than a simple brand comparison. Capacity, recovery, positioning, insulation, energy source and household habits all deserve attention.</p><a class="text-link" href="/advice/cold-weather-hot-water/">Read the cold-weather guide →</a></div><img src="/assets/technician-frost.webp" alt="Technician inspecting a heat pump hot water system on a frosty morning near Orange NSW" width="1600" height="840" loading="lazy"></section>'''
    body += f'''<section class="section"><p class="eyebrow">Services</p><h2>Start with the need, not the sales pitch</h2><p class="lead">Choose the situation closest to yours. Each guide explains what information helps and which decisions may follow.</p><div class="cards">{cards}</div></section>'''
    body += '''<section class="season-section"><img src="/assets/orange-four-seasons.webp" alt="The changing autumn winter spring and summer landscape around a home in Orange NSW" width="1800" height="760" loading="lazy"><div class="season-copy"><p class="eyebrow">Four seasons matter</p><h2>Hot water has to work beyond one mild test day</h2><p>Cold inlet water, morning frost, household routines and outdoor positioning can change how a system feels in use. Product data for the exact model matters more than broad promises.</p><div class="mini-grid"><span>{icon('leaf')} Autumn planning</span><span>{icon('sun')} Summer efficiency</span><span>{icon('drop')} Winter demand</span></div></div></section>'''
    body += f'''<section class="section local"><div><p class="eyebrow">Orange and nearby towns</p><h2>Local intent, practical reach</h2><p>The initial focus is Orange, with enquiries welcomed from Blayney, Millthorpe, Molong, Lucknow, Spring Hill and Borenore. Availability remains subject to the eventual provider's confirmed service radius.</p></div><a class="button outline" href="/locations/">View service areas</a></section>'''
    body += '''<section class="section"><p class="eyebrow">Common questions</p><h2>Useful answers before you enquire</h2>''' + faq_block(FAQS[:4]) + '</section>' + cta()
    return layout("Orange Hot Water | Repairs, Replacement and Upgrades", "Hot water repairs, replacement planning and system upgrade enquiries for Orange NSW and nearby towns.", body, "/")

def services_index():
    cards=''.join(f'<a class="card service-card" href="/services/{s}/"><span>{icon("drop")}</span><h3>{n}</h3><p>{d}</p><b>Read the guide →</b></a>' for s,(n,d) in SERVICES.items())
    body=hero("Hot water services in Orange NSW", "Find the right starting point for a fault, replacement, upgrade or system comparison.", "technician-frost.webp", "Repairs, replacements and upgrades")
    body+=f'''<section class="section"><p class="eyebrow">Service guides</p><h2>Practical pathways for different hot-water needs</h2><p class="lead">A good enquiry does not need a diagnosis. It needs clear observations: what system you have, what changed, when the problem occurs and what outcome matters most.</p><div class="cards">{cards}</div></section>'''
    body+='''<section class="section split text-first"><div><p class="eyebrow">Safety first</p><h2>Some warning signs should not wait</h2><p>Keep clear of exposed wiring, gas smells, uncontrolled leaking, scalding discharge, smoke or sparking. If water is threatening electrical equipment or the building, treat the immediate hazard seriously and contact the appropriate emergency service or licensed trade.</p><p>Online content cannot safely diagnose every fault. Photographs, error codes and a plain description can help a provider prepare, but they do not replace an on-site assessment.</p></div><div class="ochre-panel"><h3>Helpful enquiry details</h3><ul><li>System type and approximate age</li><li>Suburb and property type</li><li>Whether water is cold, lukewarm or intermittent</li><li>Visible leaks, noises or error codes</li><li>Household size and preferred timing</li></ul></div></section>'''+cta("Choose a sensible next step")
    return layout("Hot Water Services Orange NSW", "Explore hot water repair, replacement, heat pump, electric, gas and upgrade information for Orange NSW.", body, "/services/")

def service_page(slug, name, desc):
    specifics = {
      "repairs": ("A repair enquiry starts with symptoms", "Loss of hot water, changing temperature, unusual noise, leaking or repeated reset problems may have different causes. Note when the problem began and whether it affects every outlet.", ["No hot water or only lukewarm water", "Water temperature changing unexpectedly", "Visible leaking around valves, fittings or the tank", "Unusual sounds, odours or error codes"]),
      "replacement": ("Replacement is a household decision", "A rushed like-for-like swap can preserve the same capacity or running-cost problem. Compare demand, available energy, installation constraints and likely time in the property.", ["Tank corrosion or water from the cylinder", "Repeated faults on an ageing system", "Capacity no longer matches the household", "A planned efficiency or electrification upgrade"]),
      "heat-pump": ("Cold-climate detail matters", "Heat pumps transfer heat from surrounding air. They can be effective in cool climates, but the model's operating range, recovery, backup heating, noise and installation position must suit the property.", ["Exact model performance in low temperatures", "Outdoor airflow and acoustic position", "Tank capacity and recovery pattern", "Tariff, controls and electrical requirements"]),
      "electric": ("Simple equipment still needs correct sizing", "Electric storage systems are familiar and widely understood, yet running pattern, tank size, tariff and element configuration can materially affect cost and availability.", ["Element or thermostat faults", "Off-peak supply and recovery timing", "Cylinder condition and relief-valve discharge", "Household peak-use requirements"]),
      "gas": ("Fuel and flue conditions shape the choice", "Gas systems may be storage or continuous flow. Ignition, ventilation, gas supply, flue condition and water flow all require qualified assessment.", ["Ignition or pilot problems", "Temperature fluctuations at outlets", "Existing gas capacity and appliance position", "Possible future energy changes"]),
      "continuous-flow": ("Flow rate matters as much as unit size", "Continuous-flow systems heat water as it is used. Performance depends on incoming water temperature, simultaneous outlets, required temperature rise and available gas or electrical capacity.", ["Number of showers and taps used together", "Cold winter inlet temperature", "Distance to bathrooms and kitchen", "Existing services and installation position"]),
      "system-upgrades": ("Upgrade around your priorities", "An upgrade may aim to reduce running costs, improve recovery, support a larger household, move away from gas or replace a failing system before it becomes urgent.", ["Current annual or seasonal problems", "Likely household changes", "Space, noise and electrical constraints", "Upfront budget and longer-term priorities"]),
    }
    heading, text, checks=specifics[slug]
    body=hero(f"{name} in Orange NSW", desc, "technician-frost.webp", "Orange hot-water service guide")
    body+=f'''<section class="section split"><div><p class="eyebrow">What to consider</p><h2>{heading}</h2><p>{text}</p><p>Do not remove covers or attempt electrical, gas or pressure-system work yourself. A clear enquiry helps a licensed provider decide what information or attendance is needed.</p></div><div class="ochre-panel"><h3>Details worth noting</h3><ul>{''.join(f'<li>{x}</li>' for x in checks)}</ul></div></section>'''
    body+=f'''<section class="section"><p class="eyebrow">A practical process</p><h2>From symptoms to a suitable recommendation</h2><div class="steps"><article><b>01</b><h3>Describe</h3><p>Share the suburb, system type, age if known, symptoms and any safe-to-observe code or leak location.</p></article><article><b>02</b><h3>Clarify</h3><p>Explain household demand, access, timing and whether you want repair, replacement advice or an efficiency comparison.</p></article><article><b>03</b><h3>Assess</h3><p>The eventual provider confirms availability, required inspection, scope, product options and pricing.</p></article></div></section>'''
    body+='''<section class="section alt"><h2>Questions to ask before agreeing to work</h2><div class="two-col"><p><b>What is included?</b><br>Ask about removal, disposal, valves, drainage, electrical or gas work, access changes, commissioning and documentation.</p><p><b>Why this capacity?</b><br>The recommendation should relate to household use, recovery and winter conditions rather than a generic rule.</p><p><b>What remains excluded?</b><br>Unexpected access, switchboard, gas supply or building work should be identified as clearly as possible.</p><p><b>What product evidence applies?</b><br>Use the exact model's specifications, warranty terms and low-temperature data where relevant.</p></div></section>'''
    body+=f'''<section class="section"><h2>{name} questions</h2>{faq_block(FAQS[1:5])}</section>'''+cta(f"Ask about {name.lower()}")
    return layout(f"{name} Orange NSW | Orange Hot Water", f"{desc} Request a hot water enquiry for Orange NSW and nearby areas.", body, f"/services/{slug}/", "Service")

def locations_index():
    cards=''.join(f'<a class="card place-card" href="/locations/{s}/"><span class="place-dot"></span><h3>{n}</h3><p>{d}</p><b>View local guide →</b></a>' for s,(n,d) in LOCATIONS.items())
    body=hero("Hot water enquiries across Orange and nearby towns", "Orange is the core service area, supported by carefully selected nearby communities where provider coverage can be confirmed.", "orange-four-seasons.webp", "Central Tablelands service areas")
    body+=f'''<section class="section"><p class="eyebrow">Initial service radius</p><h2>Focused enough to stay useful</h2><p class="lead">Location pages should help people, not simply exchange one town name for another. Each area brings different property layouts, access patterns and exposure to Central Tablelands weather.</p><div class="cards places">{cards}</div></section>'''+cta("Check availability for your suburb or town")
    return layout("Hot Water Service Areas Near Orange NSW", "Hot water enquiry coverage for Orange, Blayney, Millthorpe, Molong, Lucknow, Spring Hill and Borenore.", body, "/locations/")

def location_page(slug,name,local):
    body=hero(f"Hot water services in {name}", f"Repair, replacement and upgrade enquiries for homes and suitable properties in {name} and the Orange region.", "orange-four-seasons.webp", f"{name} hot-water enquiries")
    body+=f'''<section class="section split"><div><p class="eyebrow">Local context</p><h2>Plan for the property and the season</h2><p>{local}</p><p>Cold-weather performance, safe access, pipework, existing energy supply and household demand should be considered together. A useful recommendation is based on the actual property and exact product, not a blanket claim about one technology.</p><p>Availability in {name} must be confirmed by the eventual provider. Orange Hot Water does not publish an invented workshop address or imply that a staffed premises operates in every location.</p></div><div class="ochre-panel"><h3>Include in your enquiry</h3><ul><li>Your suburb or locality</li><li>Current system type and age if known</li><li>Fault, leak or replacement goal</li><li>Household size and peak-use pattern</li><li>Access notes and useful photographs</li></ul></div></section>'''
    body+='''<section class="section"><p class="eyebrow">Options</p><h2>Service pathways</h2><div class="cards">''' + ''.join(f'<a class="card service-card" href="/services/{s}/"><h3>{n}</h3><p>{d}</p><b>Learn more →</b></a>' for s,(n,d) in list(SERVICES.items())[:4]) + '</div></section>'
    body+='''<section class="section alt"><h2>Before choosing a replacement</h2><div class="two-col"><p><b>Demand</b><br>Count the people, bathrooms and times when multiple outlets run together.</p><p><b>Climate</b><br>Check cold-weather and recovery data for the exact model under consideration.</p><p><b>Position</b><br>Consider airflow, noise, access, frost exposure and the distance to key outlets.</p><p><b>Scope</b><br>Confirm removal, valves, drainage, electrical or gas work and commissioning.</p></div></section>'''+cta(f"Send a {name} hot-water enquiry")
    return layout(f"Hot Water {name} | Repairs and Replacement Enquiries", f"Hot water repair, replacement and upgrade enquiries in {name}, NSW, subject to provider service coverage.", body, f"/locations/{slug}/", "Service")

def advice():
    body=hero("Hot-water advice for Orange homes", "Clear explanations for faults, replacement planning, energy choices and cold-climate performance.", "orange-four-seasons.webp", "Practical homeowner resources")
    body+='''<section class="section"><p class="eyebrow">Featured guide</p><h2>Cold mornings change the questions worth asking</h2><div class="feature-card"><img src="/assets/technician-frost.webp" alt="Hot water technician working beside a frosty Orange NSW garden" width="1600" height="840" loading="lazy"><div><h3>Cold-weather hot water in Orange</h3><p>Learn how inlet temperature, recovery, positioning, household demand and model data can affect system experience through winter.</p><a class="button outline" href="/advice/cold-weather-hot-water/">Read the guide</a></div></div></section>'''
    body+='''<section class="section alt"><h2>Questions these resources help answer</h2><div class="two-col"><p><b>Repair or replacement?</b><br>Understand the observations that help separate a component fault from a failing storage vessel.</p><p><b>Which technology?</b><br>Compare heat pump, electric, gas and continuous-flow options around the property rather than hype.</p><p><b>What affects running cost?</b><br>Capacity, controls, tariff, climate, usage and installation can all influence the outcome.</p><p><b>What belongs in a quote?</b><br>Ask about removal, disposal, connection work, access, commissioning and exclusions.</p></div></section>'''+cta()
    return layout("Hot Water Advice Orange NSW", "Practical hot-water advice for Orange NSW homes, including cold-weather performance, repairs and replacement planning.", body, "/advice/")

def cold_guide():
    body=hero("Cold-weather hot water in Orange", "What frost, low inlet temperatures and winter household demand can mean for storage, heat-pump and continuous-flow systems.", "orange-four-seasons.webp", "Orange seasonal guide")
    body+='''<article class="article"><p class="lede">Orange experiences genuine seasonal change. A hot-water system that appears generous in mild weather may feel slower when incoming water is colder and demand rises. This does not make one technology universally right or wrong; it makes accurate sizing and product-specific evidence important.</p><h2>Why winter can expose a marginal system</h2><p>When inlet water is colder, more energy is required to reach the same delivery temperature. Storage systems may take longer to recover after heavy use. Continuous-flow equipment must achieve a greater temperature rise. Heat-pump performance depends on the design and controls of the exact model, the surrounding air temperature and the way backup heating is managed.</p><p>Household behaviour matters too. Longer showers, closely timed use and guests can turn a borderline capacity into a recurring shortage. Before blaming the technology, record when the problem occurs, how many outlets are involved and whether the system later recovers.</p><h2>Heat pumps in a cool climate</h2><p>Modern heat pumps can operate in cold conditions, but broad statements are not enough. Compare the manufacturer's operating range, published cold-weather performance, recovery information, tank size and backup-element behaviour. Positioning should allow airflow and maintenance while considering bedrooms, neighbours and frost-prone corners.</p><h2>Storage-system considerations</h2><p>Electric and gas storage systems keep a volume of heated water ready. Useful questions include whether the cylinder is correctly sized, whether off-peak recovery matches the household routine, whether insulation and exposed pipework are in sound condition and whether repeated relief-valve discharge needs assessment.</p><h2>Continuous-flow considerations</h2><p>These systems heat water as required, but their delivered flow depends on the necessary temperature rise and available energy input. Winter inlet temperature, simultaneous showers and long pipe runs can affect the result. Ask for sizing that reflects the home's peak demand.</p><h2>Prepare a better enquiry</h2><ul><li>Photograph the system label without removing covers.</li><li>Record error codes and when they occur.</li><li>Note whether the problem affects all outlets.</li><li>Describe household size and simultaneous use.</li><li>Explain priorities: upfront cost, running cost, recovery, emissions, space or noise.</li></ul><p>Do not attempt electrical, gas or pressurised-water repairs yourself. Product choices and installations should be assessed by appropriately licensed providers.</p></article>'''+cta("Discuss your cold-weather hot-water needs")
    return layout("Cold Weather Hot Water Guide Orange NSW", "A practical guide to winter hot-water performance, heat pumps, storage and continuous-flow systems in Orange NSW.", body, "/advice/cold-weather-hot-water/", "Article")

def contact():
    body=hero("Request a hot-water quote", "Tell us about the property, current system and what has changed. No phone number is required to start an enquiry.", "hero-autumn-twilight.webp", "Orange NSW enquiry")
    body+=f'''<section class="section form-layout"><div><p class="eyebrow">What to include</p><h2>A few useful details can save time</h2><p>Provide what you know; you do not need to diagnose the fault. Never remove a cover or approach unsafe wiring, gas or leaking hot water simply to take a photograph.</p><ul class="ticks"><li>Suburb and property type</li><li>System type and approximate age</li><li>Fault, leak, upgrade or replacement goal</li><li>Household size and urgency</li><li>Any safe-to-observe error code</li></ul><p>Email enquiries may also be sent to <a href="mailto:{EMAIL}">{EMAIL}</a>.</p></div><form action="https://formsubmit.co/{LEAD_EMAIL}" method="POST"><input type="hidden" name="_subject" value="Orange Hot Water website enquiry"><input type="hidden" name="_template" value="table"><input type="hidden" name="_captcha" value="true"><label>Name<input name="name" required autocomplete="name"></label><label>Email<input type="email" name="email" required autocomplete="email"></label><label>Suburb or town<input name="location" required autocomplete="address-level2"></label><label>What do you need?<select name="request_type" required><option value="">Choose one</option><option>Repair or fault</option><option>Leaking system</option><option>Replacement</option><option>Heat pump upgrade</option><option>System comparison or advice</option><option>Other</option></select></label><label>Current system, symptoms and project details<textarea name="message" rows="7" required></textarea></label><label class="consent"><input type="checkbox" required> I agree that my enquiry may be shared with an authorised service provider for response and lead management.</label><button class="button" type="submit">Send enquiry</button><p class="form-note">Enquiries are delivered securely to the website owner for appropriate follow-up.</p></form></section>'''
    return layout("Contact Orange Hot Water", "Send a hot water repair, replacement or system upgrade enquiry for Orange NSW and nearby towns.", body, "/contact/", "ContactPage")

def about():
    body=hero("About Orange Hot Water", "A focused online enquiry service designed to make local hot-water decisions clearer.", "hero-autumn-twilight.webp", "Clear local information")
    body+='''<section class="section split"><div><p class="eyebrow">What this website is</p><h2>A practical connection point, not an invented shopfront</h2><p>Orange Hot Water is an independent online lead-generation and service-enquiry website. It helps people describe hot-water needs, understand sensible considerations and request contact from a suitable provider.</p><p>The site does not claim a staffed storefront, publish an artificial local address or invent trade credentials. When a service provider rents or receives enquiries from the site, their verified capabilities, availability and service radius can be added accurately.</p></div><div class="ochre-panel"><h3>What guides the content</h3><ul><li>Useful answers before marketing claims</li><li>Exact product evidence over broad promises</li><li>Clear distinction between general guidance and on-site assessment</li><li>No fake testimonials, ratings or experience claims</li></ul></div></section>'''
    body+='''<section class="section alt"><p class="eyebrow">Designed for Orange</p><h2>Cold climate, strong seasons, practical homes</h2><p class="lead">The colours and imagery draw on Orange's blue-hour skies, ochre light, autumn foliage and frosty mornings. The substance follows the same local logic: hot-water advice should recognise seasonal demand and the realities of regional properties.</p></section>'''+cta()
    return layout("About Orange Hot Water", "Learn how Orange Hot Water provides clear online hot-water information and enquiry pathways for Orange NSW.", body, "/about/", "AboutPage")

def faq_page():
    body=hero("Hot-water questions answered", "Direct, practical guidance for common repair, replacement and system-choice questions.", "technician-frost.webp", "Orange hot-water FAQ")
    body+='<section class="section"><h2>Frequently asked questions</h2>'+faq_block()+'''<p class="fine">These answers are general information. They cannot diagnose a particular system or replace advice from an appropriately licensed provider who has assessed the property.</p></section>'''+cta()
    return layout("Hot Water FAQ Orange NSW", "Answers to common questions about hot water faults, replacement, heat pumps, quotes and NSW incentives.", body, "/faq/", "FAQPage")

def legal(title, path, paragraphs):
    body=f'''<section class="simple-hero"><p class="eyebrow">Orange Hot Water</p><h1>{title}</h1><p>Last updated 27 September 2026</p></section><article class="article legal-copy">{paragraphs}</article>'''
    return layout(f"{title} | Orange Hot Water", f"{title} for the Orange Hot Water website.", body, path)

def build():
    OUT.mkdir(exist_ok=True); ASSETS.mkdir(exist_ok=True)
    write("/", home()); write("/services/", services_index())
    for s,(n,d) in SERVICES.items(): write(f"/services/{s}/", service_page(s,n,d))
    write("/locations/", locations_index())
    for s,(n,d) in LOCATIONS.items(): write(f"/locations/{s}/", location_page(s,n,d))
    write("/advice/", advice()); write("/advice/cold-weather-hot-water/", cold_guide())
    write("/about/", about()); write("/contact/", contact()); write("/faq/", faq_page())
    write("/privacy/", legal("Privacy Policy", "/privacy/", "<h2>Information collected</h2><p>When you submit an enquiry, the site may collect your name, email address, suburb, service needs and the details you choose to provide.</p><h2>How information is used</h2><p>Information is used to respond to the enquiry, assess service relevance, deliver the enquiry to authorised recipients and improve lead handling. Do not submit sensitive information that is unnecessary for the request.</p><h2>Service providers</h2><p>Enquiry information may be shared with an authorised hot-water service provider so they can respond. Website delivery, analytics, security and form services may process limited technical information.</p><h2>Your choices</h2><p>You may request access to or correction of personal information held through the website by emailing info@hotwaterorange.com.</p>"))
    write("/terms/", legal("Terms of Use", "/terms/", "<h2>General information</h2><p>The website provides general information and an enquiry pathway. It does not itself perform plumbing, electrical or gas work and does not guarantee availability, pricing, timing or a particular outcome.</p><h2>Enquiries</h2><p>Submitting a form does not create a service contract. Any scope, price, licence, insurance, warranty and scheduling arrangements must be confirmed directly with the responding provider.</p><h2>Safe use</h2><p>Do not rely on website content to undertake hazardous work. Electrical, gas and pressurised hot-water systems require appropriate qualifications and site-specific assessment.</p>"))
    write("/disclaimer/", legal("Disclaimer", "/disclaimer/", "<h2>No trade or engineering advice</h2><p>Content is general educational information. It is not a diagnosis, quotation, engineering assessment or instruction to perform regulated work.</p><h2>Programs and product information</h2><p>Rebates, incentives, tariffs, product specifications and eligibility can change. Confirm current information with official sources and the relevant provider before making a decision.</p><h2>Third-party services</h2><p>Any eventual provider is responsible for their own representations, licences, insurance, quotations, contracts and work.</p>"))

    urls=[]
    for p in OUT.rglob("index.html"):
        rel=p.relative_to(OUT)
        url="/" if rel.as_posix()=="index.html" else "/"+str(rel.parent).replace('\\','/')+"/"
        urls.append(DOMAIN+url)
    (OUT/"sitemap.xml").write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{u}</loc></url>' for u in sorted(urls))+'</urlset>',encoding='utf-8')
    (OUT/"robots.txt").write_text(f'User-agent: *\nAllow: /\nSitemap: {DOMAIN}/sitemap.xml\n',encoding='utf-8')
    (OUT/"llms.txt").write_text(f'# Orange Hot Water\n\nIndependent online information and enquiry website for hot-water repairs, replacements and upgrades in Orange NSW and selected nearby towns.\n\nCanonical site: {DOMAIN}/\nSitemap: {DOMAIN}/sitemap.xml\nContact: {EMAIL}\n\nCore resources: /services/, /locations/, /advice/, /faq/\n',encoding='utf-8')

if __name__ == "__main__": build()
